[toolchain]

[features]
resolution = true
skip-lint = true

[programs.localnet]
vault = "EY1mGiYQgaLZW2fNNUjYZRNRqjDgXGZAST1endGDxjKP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./test-validator/test-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
